### ISSUE TITLE
Fix spelling typos in read more page

### ISSUE THREAD

**Issue by Mldamico** [mohitahlawat2001/box-office-react#1]
There are some typos in the read more page, such as "generes"

**Comment by HeetVekariya** [comment]
Can you locate the exact file for this issue ?

**Comment by Mldamico** [comment]
Yea, in shows > ShowMainData.

**Comment by HeetVekariya** [comment]
Is the only file need to be corrected or any other files as well ?
If it is then locate all.
I can work on it.
