### ISSUE TITLE
[feat] : Add better loading UI or any spinner when you load data.

### ISSUE THREAD

**Issue by love-sonkar** [mohitahlawat2001/box-office-react#18]
we can add better loading state for loading data

# video 

https://github.com/mohitahlawat2001/box-office-react/assets/82786865/c92daeed-905f-4265-8b92-758d025bffc0

**Comment by mohitahlawat2001** [comment]
can you change 
text "data is loading " with gif of Pikachu running.

**Comment by love-sonkar** [comment]
yes i can i'm started working on it
