### ISSUE TITLE
Change background colour to be more dynamic & add hover to button

### ISSUE THREAD

**Issue by accodes21** [mohitahlawat2001/box-office-react#3]
The background is too simple to catch the users' attention, we should work on it to make it more dynamic by adding a great background gradient.
Also add a bit of hover effect to the search button

**Comment by Prakharpandey007** [comment]
Please assign me this issue .I will make sure that all of your point is fulfilled.
Thanks You .Looking for better response.

**Comment by accodes21** [comment]
I have done the hover effect for the search button but couldn't do the background changes. Anyone amongst @Akash2866 @Prakharpandey007 proceed to do that
