### ISSUE TITLE
Fixing Show cards look

### ISSUE THREAD

**Issue by princepal-dev** [mohitahlawat2001/box-office-react#4]
Add a background border in the show cards and make the read more button look better by adding background color and removing the text underline.

@mohitahlawat2001 

[https://drive.google.com/file/d/1tjdEkMmiHhP02hxvAtp_mWsuxUHgyw-7/view?usp=sharing](url)

**Comment by Prakharpandey007** [comment]
Please assign me this issue. I will make sure that all of your points are fulfilled .
Thank you, looking forward for great response .
